### ISSUE TITLE
intelmq-dev needs to add intelmq to sudoers file

### ISSUE THREAD

**Issue by waldbauer-certat** [certat/intelmq-docker#17]
@einar-lanfranco As stated here https://github.com/certtools/intelmq/issues/2261, intelmq-full-dev is not able to install any packages during the run. You need to add intelmq to sudoers. To achieve this, see here

```Dockerfile
RUN useradd -d /opt/intelmq -U -s /bin/bash intelmq \
    && adduser intelmq sudo \
    && echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /opt/sudoers \
```

**Comment by waldbauer-certat** [comment]
But thats strange, intelmq-full-dev builds upon intelmq-full where the user intelmq is in sudo... Have to investigate a bit further

**Comment by einar-lanfranco** [comment]
Hi, sudoers its /etc/sudoers, not /opt/sudoers.

**Comment by waldbauer-certat** [comment]
My bad, sorry.
