### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by norbertbonnici** [certat/intelmq-docker#7]
What is the default password used in this docker image? intelmq : intelmq does not seem to work.

**Comment by wagner-certat** [comment]
You mean the default password for the IntelMQ Manager interface? AFAIK there is none.

Adding a user is explained here: https://intelmq.readthedocs.io/en/maintenance/user/intelmq-api.html#adding-a-user

**Comment by norbertbonnici** [comment]
In the docker cli, when intelmq-api-adduser is used, this error is issued:

```
Traceback (most recent call last):
  File "intelmq-api-adduser", line 12, in <module>
    import intelmq_api.config
ModuleNotFoundError: No module named 'intelmq_api'
```

**Comment by wagner-certat** [comment]
To run the command inside the docker-container, you need to run `docker-compose exec intelmq $command` if the container is not running or `docker exec -it <container name> /bin/bash $command` if the container is running

**Comment by norbertbonnici** [comment]
The same error is issued when docker exec is used: 
```
intelmq@590daee1c411:/opt/intelmq-api/scripts$ python3 intelmq-api-adduser --user norbert --password bonnici
Traceback (most recent call last):
  File "intelmq-api-adduser", line 12, in <module>
    import intelmq_api.config
ModuleNotFoundError: No module named 'intelmq_api'
```

**Comment by waldbauer-certat** [comment]
I'm currently fixing the Dockerfile so it in the next few days it should be possible to add an intelmq user within environment variables
```
INTELMQ_API_NAME=
INTELMQ_API_PASS=
```
or something similiar.

In the latest push I've fixed the intelmq-api-adduser command, its possible to add them now.

Thanks for the report :)

**Comment by waldbauer-certat** [comment]
Hello @norbertbonnici 

I've recently pushed an update where you can set the username & password for the intelmq-api.

i. e. in the docker-compose file, in the intelmq section
```
            INTELMQ_API_USER: "abc"
            INTELMQ_API_PASS: "123"
```

**Comment by norbertbonnici** [comment]
Works - thanks!
